assetregister/urls.py
from django.conf.urls import include, url
from . import views
# from assetregister.views import NewSearchView
from django.conf import settings

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^calibration/$', views.calibration_list, name="calibration_list"),
    url(r'^calibration/new/$', views.new_calibration, name="new_calibration"),
    url(r'^calibration/new/(?P<urlpk>\d+)/$', views.new_calibration_asset, name="new_calibration_asset"),
    url(r'^calibration/assets/$', views.calibrated_asset_list, name="calibrated_asset_list"),
    url(r'^calibration/assets/active$', views.calibrated_asset_list_active, name="calibrated_asset_list_active"),
    url(r'^calibration/export/active/$', views.calibrated_asset_export_active, name="calibrated_asset_export_active"),
    url(r'^calibration/export/all/$', views.calibrated_asset_export_all, name="calibrated_asset_export_all"),
    url(r'^calibration/export/all/nextmonth/$', views.calibration_asset_export_nextmonth,
        name="calibration_asset_export_nextmonth"),
    url(r'^calibration/export/custom/$', views.calibration_asset_export_custom, name="calibration_asset_export_custom"),
    url(r'^calibration/export/$', views.calibration_asset_export_custom_select,
        name="calibration_asset_export_custom_select"),
    url(r'^calibration/export/records/$', views.export_all_calibrations, name="export_calibration_records"),
    url(r'^calibration/(?P<slug>[-\w]+)/$', views.calibration_detail, name="calibration_detail"),
    url(r'^calibration/(?P<slug>[-\w]+)/edit$', views.calibration_edit, name="calibration_edit"),
    url(r'^calibration/(?P<slug>[-\w]+)/remove/$', views.calibration_confirm_delete.as_view(), name="calibration_confirm_delete"),
    url(r'^asset/$', views.asset_list, name="asset_list"),
    url(r'^asset/active/$', views.active_asset_list, name="active_asset_list"),
    url(r'^asset/new/$', views.asset_new, name="asset_new"),
    url(r'^asset/new/calibration$', views.calibration_asset_new, name="calibration_asset_new"),
    url(r'^asset/bulk_reserve/$', views.reserve_assets, name="reserve_assets"),
    url(r'^asset/bulk_reserve/print/(?P<id_from>\d+)/(?P<id_to>\d+)/$', views.print_asset_labels, name="print_asset_labels"),
    url(r'^asset/(?P<pk>\d+)/edit/calibration/$', views.edit_asset_calibration_info, name="edit_asset_calibration_info"),
    url(r'^asset/(?P<pk>\d+)/edit/finance/$', views.edit_asset_finance_info, name="edit_asset_finance_info"),
    url(r'^asset/(?P<pk>\d+)/edit/location/$', views.edit_asset_location, name="edit_asset_location"),
    url(r'^asset/(?P<pk>\d+)/edit/$', views.asset_edit, name="asset_edit"),
    url(r'^asset/(?P<pk>\d+)/remove/$', views.asset_confirm_delete.as_view(), name="asset_confirm_delete"),
    url(r'^asset/(?P<pk>\d+)/qr/small/$', views.asset_qr_small, name="asset_qr_small"),
    url(r'^asset/(?P<pk>\d+)/qr/$', views.asset_qr, name="asset_qr"),
    url(r'^asset/(?P<pk>\d+)/$', views.asset_detail, name="asset_detail"),
    url(r'^asset/equip-id/(?P<equipid>[-\w]+)/$', views.asset_detail_equipid, name="asset_detail_equipid"),
    url(r'^location/$', views.qr_location_list, name="qr_location_list"),
    url(r'^location/new$', views.new_qr_location, name="new_qr_location"),
    url(r'^location/(?P<pk>\d+)/edit/$', views.edit_qr_location, name="edit_qr_location"),
    url(r'^location/(?P<pk>\d+)/qr/$', views.qr_location_qr, name="qr_location_qr"),
    url(r'^location/(?P<pk>\d+)/view/$', views.qr_location_view_assets, name="qr_location_view_assets"),
    url(r'^location/(?P<pk>\d+)/$', views.move_asset_to_qr_location, name="move_asset_to_qr_location"),
    url(r'^location/bulk_reserve/$', views.reserve_qr_locations, name="reserve_qr_locations"),
    url(r'^location/bulk_reserve/print/(?P<id_from>\d+)/(?P<id_to>\d+)/$', views.print_location_labels, name="print_location_labels"),
    url(r'^search/', include("haystack.urls")),
    url(r'^search/advanced/$', views.asset_list_filter, name="asset_list_filter"),
    url(r'^asset/export/all/$', views.export_all_assets, name="asset_export_all"),
    url(r'^maintenance/export/all/$', views.maintenance_export_all, name="maintenance_export_all"),
    url(r'^environmental/export/all/$', views.environmental_export_all, name="environmental_export_all"),
    url(r'^insurance/export/all/$', views.insurance_export_all, name="insurance_export_all"),
    url(r'^safety/export/all/$', views.safety_export_all, name="safety_export_all"),
    # url(r'^newsearch/?$', NewSearchView.as_view(), name='new_search_view'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^staff/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'', include('assetregister.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#    urlpatterns += (
#        url(r'^media/(?P<path>.*)$', "django.views.static.serve", {'document_root': settings.MEDIA_ROOT, }),
#    )

assetregister/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
import os
from haystack.management.commands import update_index
import logging
import uuid
from background_task import background

logger = logging.getLogger(__name__)


@background()
def reindex_whoosh():
    update_index.Command().handle(interactive=False, remove=True, age=1)
    # age=1 will only add assets edited in last hour.


default_asset_status = 1


CALIBRATION_TYPE = (
                       ("Internal", "Internal"),
                       ("External", "External")
                     )


class Asset(models.Model):
    asset_id = models.AutoField(primary_key=True)
    asset_description = models.CharField(max_length=200)
    asset_image = models.ImageField(upload_to="images/temp", max_length=255, null=True, blank=True)
    asset_image_thumbnail = models.ImageField(upload_to="images", editable=False, null=True)
    asset_details = models.TextField(blank=True)
    asset_manufacturer = models.CharField(max_length=255, blank=True)
    asset_model = models.CharField(max_length=255, null=True, blank=True)
    asset_serial_number = models.CharField(max_length=255, null=True, blank=True)
    amrc_equipment_id = models.CharField(max_length=16, null=True, blank=True)
    handling_and_storage_instructions = models.URLField(max_length=255, null=True, blank=True)
    operating_instructions = models.URLField(max_length=255, null=True, blank=True)
    asset_status = models.ForeignKey("AssetStatus", on_delete=models.SET_NULL, null=True, default=default_asset_status, related_name="status")
    person_responsible = models.CharField(max_length=100)
    person_responsible_email = models.EmailField()
    amrc_group_responsible = models.ForeignKey("AmrcGroup", on_delete=models.SET_NULL, blank=True, null=True, related_name="amrc_group")
    requires_insurance = models.BooleanField()
    requires_unforseen_damage_insurance = models.BooleanField(default=False)
    requires_safety_checks = models.BooleanField()
    safety_notes = models.TextField(null=True, blank=True)
    requires_environmental_checks = models.BooleanField()
    environmental_aspects = models.ManyToManyField("EnvironmentalAspects", blank=True)
    environmental_notes = models.TextField(null=True, blank=True)
    emergency_response_information = models.TextField(null=True, blank=True)
    requires_planned_maintenance = models.BooleanField()
    maintenance_instructions = models.URLField(max_length=255, null=True, blank=True)
    maintenance_records = models.URLField(max_length=255, null=True, blank=True)
    maintenance_notes = models.TextField(blank=True, null=True)
    requires_calibration = models.BooleanField()
    calibration_frequency = models.CharField(max_length=64, null=True, blank=True)
    passed_calibration = models.BooleanField(default=False)
    calibration_date_prev = models.DateField(null=True, blank=True)
    calibration_date_next = models.DateField(null=True, blank=True)
    calibration_procedure = models.TextField(blank=True)
    calibration_status = models.ForeignKey("CalibrationStatus", on_delete=models.SET_NULL, blank=True, null=True, related_name="calibration_status")
    calibration_type = models.CharField(max_length=10, choices=CALIBRATION_TYPE, default="Internal", blank=True, null=True)
    asset_value = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    charge_out_rate = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    charge_code = models.CharField(max_length=64, null=True, blank=True)
    purchase_order_ref = models.CharField(max_length=15, null=True, blank=True)
    grn_id = models.CharField(max_length=12, null=True, blank=True)
    funded_by = models.CharField(max_length=255, null=True, blank=True)
    acquired_on = models.DateField(null=True, blank=True)
    disposal_date = models.DateField(null=True, blank=True)
    disposal_method = models.CharField(max_length=255, null=True, blank=True)
    dispatch_note_id = models.CharField(max_length=12, null=True, blank=True)
    parent_assets = models.ManyToManyField("self", blank=True)
    asset_location_building = models.ForeignKey("Buildings", on_delete=models.SET_NULL, blank=True, null=True, related_name="building")
    asset_location_room = models.CharField(max_length=255, blank=True)
    asset_qr_location = models.ForeignKey("QRLocation", on_delete=models.SET_NULL, blank=True, null=True, related_name="asset_qr_location_id")
    edited_by = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True)
    edited_on = models.DateTimeField(default=timezone.now)

    def image_move_rename():
        pass

    def image_thumbnail():
        pass

    def image_watermark():
        pass

    def save(self, *args, **kwargs):
        # Custom save function to generate an asset ID / PK needed to rename files,_
        # move and rename image upload and create thumbnail
        # If now have a QRLocationID update location building and room info

        # Call save first, to create a primary key
        super(Asset, self).save(*args, **kwargs)

        # Check if have any asset image (newly uploaded, or kept from previous upload)
        asset_image = self.asset_image
        if asset_image:

            # If asset_image.name contains "/temp" then it's newly uploaded so rename, move, thumbnail and watermark
            if "images/temp" in self.asset_image.name:

                # image_move_rename()
                # image_thumbnail()
                # image_watermark()

                # If have a newly uploaded image then import the things needed to make watermark & thumbnail
                from django.core.files.base import ContentFile
                from django.core.files.storage import default_storage as storage
                from io import BytesIO
                from PIL import Image

                # Create image filename using pk / asset_ID and original file extension
                oldfile = self.asset_image.name
                lastdot = oldfile.rfind(".")
                newfile = "images/" + str(self.pk) + oldfile[lastdot:]

                # Create image with new filename, remove old image if "filepath"_
                # (really only file extension!) is now different
                if newfile != oldfile:
                    self.asset_image.storage.delete(newfile)
                    self.asset_image.storage.save(newfile, asset_image)
                    self.asset_image.name = newfile
                    self.asset_image.close()
                    self.asset_image.storage.delete(oldfile)

                oldthumbnail = self.asset_image_thumbnail
                if oldthumbnail:
                    # Delte old thumb
                    oldthumbname = self.asset_image_thumbnail.name
                    self.asset_image_thumbnail.storage.delete(oldthumbname)

                # Save changes
                super(Asset, self).save(*args, **kwargs)

                # -- THUMBNAIL --
                THUMB_SIZE = (300, 200)

                # Open image to thumbnail
                fh = storage.open(self.asset_image.name)
                image = Image.open(fh)

                # Check if image smaller than requested thumb size,
                # ...if so don't thumb or will raise error

                if image.size[0] <= THUMB_SIZE[0] or image.size[1] <= THUMB_SIZE[1]:
                    self.asset_image_thumbnail.name = self.asset_image.name
                else:
                    image.thumbnail(THUMB_SIZE, Image.ANTIALIAS)
                    fh.close()

                    thumb_name, thumb_extension = os.path.splitext(self.asset_image.name)
                    thumb_extension = thumb_extension.lower()
                    thumb_filename = thumb_name + "_thumb" + thumb_extension

                    if thumb_extension in [".jpg", ".jpeg"]:
                        FTYPE = "JPEG"
                    elif thumb_extension == ".gif":
                        FTYPE = "GIF"
                    elif thumb_extension == ".png":
                        FTYPE = "PNG"
                    else:
                        raise Exception("Error creating thumnail. Image must be a .jpg, .jpeg, .gif or .png!")

                    temp_thumb = BytesIO()
                    image.save(temp_thumb, FTYPE, quality=100)
                    temp_thumb.seek(0)
                    self.asset_image_thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
                    temp_thumb.close()

                # -- WATERMARK --
                assetimage = storage.open(self.asset_image.name)
                logoimage = storage.open("images/watermarklogo4.png")
                img = Image.open(assetimage).convert("RGBA")
                logo = Image.open(logoimage).convert("RGBA")

                img_w = img.size[0]
                img_h = img.size[1]

                # resize logo to be quarter of asset_image width, but same aspect ratio
                logo_aspect_ratio = float(logo.size[0] / logo.size[1])

                # If image width or height <= 400 resize logo to be half, else 1/4th of image's shortest side
                if img_w > img_h:
                    if img_w <= 400:
                        logo_w = int(img_w / 2)
                    else:
                        logo_w = int(img_w / 4)
                    logo_h = int(logo_w / logo_aspect_ratio)
                else:
                    if img_h <= 400:
                        logo_h = int(img_h / 2)
                    else:
                        logo_h = int(img_h / 4)
                    logo_w = int(logo_h * logo_aspect_ratio)

                logo = logo.resize((logo_w, logo_h), Image.ANTIALIAS)

                # position the watermark centrally
                offset_x = ((img.size[0]) / 2) - ((logo.size[0]) / 2)
                offset_y = ((img.size[1]) / 2) - ((logo.size[1]) / 2)

assetregister/templates/assetregister/asset_list_filtered2.html
{% extends 'assetregister/base.html' %}

{% block content %}

	<ul class="breadcrumb">
	  <li><a href="/">Home</a></li>
	  <li><a href="/search">Search</a></li>
	  <li class="active">Advanced Search</li>
	</ul>

	<h3>Advanced Search</h3>
	
	<h5>All filters on this form are combined
		<br />e.g. Asset model contains "X" AND Asset serial number contains "Y"</h5>
	<br />	
	
	<form action="" method="get" class="form-horizontal asset-form">
		<fieldset>
			<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_requires_calibration">Requires calibration:</label></label>
					<div class="col-lg-6">
						<select id="id_requires_calibration" name="requires_calibration">
							<option value="1" selected="selected">Unknown</option>
							<option value="2">Yes</option>
							<option value="3">No</option>
						</select>
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_passed_calibration">Passed calibration:</label></label>
					<div class="col-lg-6">
						<select id="id_passed_calibration" name="passed_calibration">
							<option value="1" selected="selected">Unknown</option>
							<option value="2">Yes</option>
							<option value="3">No</option>
						</select>
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_requires_safety_checks">Requires safety checks:</label></label>
					<div class="col-lg-6">
						<select id="id_requires_safety_checks" name="requires_safety_checks">
							<option value="1" selected="selected">Unknown</option>
							<option value="2">Yes</option>
							<option value="3">No</option>
						</select>
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_requires_environmental_checks">Requires environmental checks:</label></label>
					<div class="col-lg-6">
						<select id="id_requires_environmental_checks" name="requires_environmental_checks">
							<option value="1" selected="selected">Unknown</option>
							<option value="2">Yes</option>
							<option value="3">No</option>
						</select>
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_requires_planned_maintenance">Requires planned maintenance:</label></label>
					<div class="col-lg-6">
						<select id="id_requires_planned_maintenance" name="requires_planned_maintenance">
							<option value="1" selected="selected">Unknown</option>
							<option value="2">Yes</option>
							<option value="3">No</option>
						</select>
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_requires_insurance">Requires insurance:</label></label>
					<div class="col-lg-6">
						<select id="id_requires_insurance" name="requires_insurance">
						<option value="1" selected="selected">Unknown</option>
						<option value="2">Yes</option>
						<option value="3">No</option>
						</select>
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_calibration_date_next__gt">Calibration date next calibration date next is greater than:</label></label>
					<div class="col-lg-6">
						<input id="id_calibration_date_next__gt" name="calibration_date_next__gt" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_calibration_date_next__lt">Calibration date next calibration date next is less than:</label></label>
					<div class="col-lg-6">
						<input id="id_calibration_date_next__lt" name="calibration_date_next__lt" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_id">Asset id:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_id" name="asset_id" step="any" type="number" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_description">Asset description contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_description" name="asset_description" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_details">Asset details contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_details" name="asset_details" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_manufacturer">Asset manufacturer contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_manufacturer" name="asset_manufacturer" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_model">Asset model contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_model" name="asset_model" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_serial_number">Asset serial number contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_serial_number" name="asset_serial_number" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_amrc_equipment_id">Amrc equipment id contains:</label></label>
					<div class="col-lg-6">
						<input id="id_amrc_equipment_id" name="amrc_equipment_id" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_person_responsible">Person responsible contains:</label></label>
					<div class="col-lg-6">
						<input id="id_person_responsible" name="person_responsible" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_person_responsible_email">Person responsible email contains:</label></label>
					<div class="col-lg-6">
						<input id="id_person_responsible_email" name="person_responsible_email" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_environmental_notes">Environmental notes contains:</label></label>
					<div class="col-lg-6">
						<input id="id_environmental_notes" name="environmental_notes" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_safety_notes">Safety notes contains:</label></label>
					<div class="col-lg-6">
						<input id="id_safety_notes" name="safety_notes" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_emergency_response_information">Emergency response information contains:</label></label>
					<div class="col-lg-6">
						<input id="id_emergency_response_information" name="emergency_response_information" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_maintenance_notes">Maintenance notes contains:</label></label>
					<div class="col-lg-6">
						<input id="id_maintenance_notes" name="maintenance_notes" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_value__gt">Asset value is greater than:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_value__gt" name="asset_value__gt" step="any" type="number" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_value__lt">Asset value is less than:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_value__lt" name="asset_value__lt" step="any" type="number" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_purchase_order_ref">Purchase order ref:</label></label>
					<div class="col-lg-6">
						<input id="id_purchase_order_ref" name="purchase_order_ref" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_funded_by">Funded by contains:</label></label>
					<div class="col-lg-6">
						<input id="id_funded_by" name="funded_by" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_acquired_on__gt">Acquired on acquired on is greater than:</label></label>
					<div class="col-lg-6">
						<input id="id_acquired_on__gt" name="acquired_on__gt" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_acquired_on__lt">Acquired on acquired on is less than:</label></label>
					<div class="col-lg-6">
						<input id="id_acquired_on__lt" name="acquired_on__lt" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_disposal_date__gt">Disposal date disposal date is greater than:</label></label>
					<div class="col-lg-6">
						<input id="id_disposal_date__gt" name="disposal_date__gt" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_disposal_date__lt">Disposal date disposal date is less than:</label></label>
					<div class="col-lg-6">
						<input id="id_disposal_date__lt" name="disposal_date__lt" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_location_building__building_name">Asset location building building name contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_location_building__building_name" name="asset_location_building__building_name" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_location_building__EFM_building_code">Asset location building efm building code contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_location_building__EFM_building_code" name="asset_location_building__EFM_building_code" type="text" />
					</div>
				</div>
			
				<div class="form-group">
					<label for="inputEmail" class="col-lg-3 control-label"><label for="id_asset_location_room">Asset location room contains:</label></label>
					<div class="col-lg-6">
						<input id="id_asset_location_room" name="asset_location_room" type="text" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-lg-3 col-lg-offset-3">
						<button type="reset" class="btn btn-default">
							Cancel
						</button>
						<button type="submit" class="btn btn-primary">
							Submit
						</button>
					</div>
				</div>
		</fieldset>
    </form>
    
	<br />
	<br />
	
    {% for asset in filter.qs %}
    	<div class="asset">
            <a href="{% url 'asset_detail' pk=asset.pk %}"><h3>{{ asset.asset_description }}</h3></a>
            
            <p>AMRC Asset Number: {{ asset.asset_id }} </p>
            
            {% if asset.asset_manufacturer %}
                <p>Manufacturer: {{ asset.asset_manufacturer }}</p> 
            {% endif %}
            
            {% if asset.asset_location_building %}
                Location (Building): {{ asset.asset_location_building }} 
            {% endif %}
            
            {% if asset.asset_location_room %}
                <br />Location (Area): {{ asset.asset_location_room }} 
            {% endif %}
            <hr>
        </div>
    {% endfor %}

	<div class="pagination">
		{% if filter.qs.paginator.count %}
		    Showing {{ filter.qs.object_list|length }} of {{ filter.qs.paginator.count }} Results on Page {{ filter.qs.number }} of {{ filter.qs.paginator.num_pages }}
		    <br />
		{% endif %}
		
		{% if filter.qs.has_previous or assets.has_next %}
			<ul class="pager">
				{% if filter.qs.has_previous %}
					<li class="previous"><a href="?page={{ filter.qs.previous_page_number }}">&laquo; Previous</a></li>
				{% else %}
					<li class="previous disabled"><a href="">&laquo; Previous</a></li>
				{% endif %}
				
				{% if filter.qs.has_next %}
					<li class="next"><a href="?page={{ filter.qs.next_page_number }}">Next &raquo;</a></li>
				{% else %}
					<li class="next disabled"><a href="">Next &raquo;</a></li>
				{% endif %}
			</ul>
		{% endif %}
	</div>
    
{% endblock %}

assetregister/templates/assetregister/simple_message.html
{% extends 'assetregister/base.html' %}
{% block content %}
{% load has_group %}

<h2>{{ message }}</h2>

{% if smallmessage %}
	{{ smallmessage }}
{% endif %}

<br /><br />

<a href="{{request.META.HTTP_REFERER}}" class="btn btn-default">Back</a>

{% if request.user|has_group:"SuperUser" %}
	{% if print_labels %}
		<br /><br />
		<a href="{% url 'print_asset_labels' id_from=earliest_asset_no id_to=latest_asset_no %}" class="btn btn-primary"> Print Asset Tags Now </a>
	{% endif %}
{% endif %}

{% endblock %}